var searchResults = { 
  "results" :[

 {
    "id":0,
    "name":"Aviation",
    "base":"Gin",
    "profile":["Spirit Forward","Fruity"],
    "Glass":"Coupe",
    "glasstype":"images/coupe_icon.svg",
    "Mix":"Shaken",
    "available":"",
    "strength":"Strong",
    "Type":"Classic",
    "served":"Up"
  },
  {
    "id":1,
    "name":"Boulevardier",
    "base":"Rye",
    "profile":["Bitter","Sweet"],
    "Glass":"Coupe",
    "glasstype":"images/coupe_icon.svg",
    "Mix":"Stirred",
    "available":"",
    "strength":"Medium",
    "Type":"Classic",
    "served":"Up"
  },
  {
    "id":2,
    "name":"Bourbon Rickey",
    "base":"Bourbon",
    "profile":["Bubbly"],
    "Glass":"Collins",
    "glasstype":"images/collins_icon.svg",
    "Mix":"Stirred",
    "available":"",
    "strength":"Meduim",
    "Type":"classic",
    "served":"On The Rocks"
  },
  {
    "id":3,
    "name":"Brown Derby",
    "base":"Bourbon",
    "profile":["Fruity","Sweet"],
    "Glass":"Coupe",
    "glasstype":"images/coupe_icon.svg",
    "Mix":"Shaken",
    "available":"",
    "strength":"Meduim",
    "Type":"Classic",
    "served":"Up"
  },
  {
    "id":4,
    "name":"Corpse Reviver",
    "base":"Gin",
    "profile":["Spirit Forward","Sour"],
    "Glass":"Coupe",
    "glasstype":"images/coupe_icon.svg",
    "Mix":"Shaken",
    "available":"",
    "strength":"Strong",
    "Type":"Classic",
    "served":"Up"
  },
  {
    "id":5,
    "name":"Daiquiri",
    "base":"Rum",
    "profile":["Fruity","Sweet"],
    "Glass":"Coupe",
    "glasstype":"images/coupe_icon.svg",
    "Mix":"Shaken",
    "available":"",
    "strength":"Medium",
    "Type":"Tiki",
    "served":"Up"
  },
  {
    "id":6,
    "name":"Elderfashion",
    "base":"Bourbon",
    "profile":["Spirit Forward","Sweet"],
    "Glass":"Rocks",
    "glasstype":"images/rocks_icon.svg",
    "Mix":"Stirred",
    "available":"",
    "strength":"Strong",
    "Type":"Classic",
    "served":"On The Rocks"
  },
  {
    "id":7,
    "name":"French 75",
    "base":"Gin",
    "profile":["Bubbly","Sweet"],
    "Glass":"Flute",
    "glasstype":"images/flute_icon.svg",
    "Mix":"Stirred",
    "available":"",
    "strength":"Medium",
    "Type":"Classic",
    "served":"Up"
  },
  {
    "id":8,
    "name":"Gimlet",
    "base":"Gin",
    "profile":["Spirit Forward","Sour"],
    "Glass":"Coupe",
    "glasstype":"images/coupe_icon.svg",
    "Mix":"Shaken",
    "available":"",
    "strength":"Strong",
    "Type":"Classic",
    "served":"Up"
  },
  {
    "id":9,
    "name":"Gin Buck",
    "base":"Gin",
    "profile":["Bubbly","Sweet"],
    "Glass":"Collins",
    "glasstype":"images/collins_icon.svg",
    "Mix":"Stirred",
    "available":"",
    "strength":"Medium",
    "Type":"Classic",
    "served":"On The Rocks"
  },
    {
    "id":10,
    "name":"Sazarac",
    "base":"Rye",
    "profile":["Spirit Forward"],
    "Glass":"Rocks",
    "glasstype":"images/rocks_icon.svg",
    "Mix":"Stirred",
    "available":"",
    "strength":"Strong",
    "Type":"Classic",
    "served":"Neat"
  }

]};